FROM node:10-alpine AS alpine

WORKDIR /app

COPY package*.json ./

## install only the packages defined in the package-lock.json
RUN npm install

# Copy the contents of the project to the image
COPY . .

# Run 'npm start' when the container starts.
CMD ["npm", "run", "start"]